local modpath = core.get_modpath(core.get_current_modname())

for _, name in ipairs({
	"doc_identifier",
	"mcl_armor",
	"mcl_armor_stand",
	"mcl_bamboo",
	"mcl_beds",
	"mcl_bells",
	"mcl_boats",
	"mcl_bows",
	"mcl_brewing",
	"mcl_buckets",
	"mcl_clock",
	"mcl_compass",
	"mcl_copper",
	"mcl_core",
	"mcl_crafting_table",
	"mcl_crimson",
	"mcl_doors",
	"mcl_dyes",
	"mcl_enchanting",
	"mcl_end",
	"mcl_farming",
	"mcl_fences",
	"mcl_fire",
	"mcl_fireworks",
	"mcl_flowers",
	"mcl_flowerpots",
	"mcl_hoppers",
	"mcl_jukebox",
	"mcl_mangrove",
	"mcl_mobitems",
	"mcl_monster_eggs",
	"mcl_mushrooms",
	"mcl_panes",
	"mcl_pressureplates",
	"mcl_redstone",
	"mcl_signs",
	"mcl_stairs",
	"mcl_tools",
	"mcl_totems",
	"mcl_trees",
	"mcl_villages",
	"mcl_wool",
	"screwdriver",
}) do
	dofile(modpath .. "/" .. name .. ".lua")
end
