core.register_alias("mcl_core:birchtree","mcl_trees:tree_birch")
core.register_alias("mcl_core:darktree","mcl_trees:tree_dark_oak")
core.register_alias("mcl_core:acaciatree","mcl_trees:tree_acacia")
core.register_alias("mcl_core:jungletree","mcl_trees:tree_jungle")
core.register_alias("mcl_core:sprucetree","mcl_trees:tree_spruce")
core.register_alias("mcl_core:tree","mcl_trees:tree_oak")
core.register_alias("default:tree","mcl_trees:tree_oak")
core.register_alias("mcl_mangrove:mangrove_tree","mcl_trees:tree_mangrove")
core.register_alias("mcl_crimson:crimson_hyphae","mcl_trees:tree_crimson")
core.register_alias("mcl_crimson:warped_hyphae","mcl_trees:tree_warped")
core.register_alias("mcl_bamboo:bamboo_block","mcl_trees:tree_bamboo")
core.register_alias("mcl_cherry_blossom:cherrytree","mcl_trees:tree_cherry_blossom")

core.register_alias("mcl_core:birchleaves","mcl_trees:leaves_birch")
core.register_alias("mcl_core:darkleaves","mcl_trees:leaves_dark_oak")
core.register_alias("mcl_core:acacialeaves","mcl_trees:leaves_acacia")
core.register_alias("mcl_core:jungleleaves","mcl_trees:leaves_jungle")
core.register_alias("mcl_core:spruceleaves","mcl_trees:leaves_spruce")
core.register_alias("mcl_core:leaves","mcl_trees:leaves_oak")
core.register_alias("default:leaves","mcl_trees:leaves_oak")
core.register_alias("mcl_mangrove:mangroveleaves","mcl_trees:leaves_mangrove")
core.register_alias("mcl_cherry_blossom:cherryleaves","mcl_trees:leaves_cherry_blossom")
core.register_alias("default:acacia_tree", "mcl_core:acaciatree")
core.register_alias("default:acacia_leaves", "mcl_core:acacialeaves")

core.register_alias("mcl_core:birchleaves_orphan","mcl_trees:leaves_birch_orphan")
core.register_alias("mcl_core:darkleaves_orphan","mcl_trees:leaves_dark_oak_orphan")
core.register_alias("mcl_core:acacialeaves_orphan","mcl_trees:leaves_acacia_orphan")
core.register_alias("mcl_core:jungleleaves_orphan","mcl_trees:leaves_jungle_orphan")
core.register_alias("mcl_core:spruceleaves_orphan","mcl_trees:leaves_spruce_orphan")
core.register_alias("mcl_core:leaves_orphan","mcl_trees:leaves_oak_orphan")
core.register_alias("mcl_mangrove:mangroveleaves_orphan","mcl_trees:leaves_mangrove_orphan")

core.register_alias("mcl_core:birchwood","mcl_trees:wood_birch")
core.register_alias("mcl_core:big_oakwood","mcl_trees:wood_dark_oak")
core.register_alias("mcl_core:darkwood","mcl_trees:wood_dark_oak")
core.register_alias("mcl_core:acaciawood","mcl_trees:wood_acacia")
core.register_alias("mcl_core:junglewood","mcl_trees:wood_jungle")
core.register_alias("mcl_core:sprucewood","mcl_trees:wood_spruce")
core.register_alias("mcl_core:wood","mcl_trees:wood_oak")
core.register_alias("mcl_crimson:warped_hyphae_wood","mcl_trees:wood_warped")
core.register_alias("mcl_crimson:crimson_hyphae_wood","mcl_trees:wood_crimson")
core.register_alias("mcl_mangrove:mangrove_wood","mcl_trees:wood_mangrove")
core.register_alias("default:wood","mcl_trees:wood_oak")
core.register_alias("mcl_bamboo:bamboo_plank","mcl_trees:wood_bamboo")
core.register_alias("mcl_cherry_blossom:cherrywood","mcl_trees:wood_cherry_blossom")

core.register_alias("mcl_core:birchtree_bark","mcl_trees:bark_birch")
core.register_alias("mcl_core:big_oaktree_bark","mcl_trees:bark_dark_oak")
core.register_alias("mcl_core:darktree_bark","mcl_trees:bark_dark_oak")
core.register_alias("mcl_core:acaciatree_bark","mcl_trees:bark_acacia")
core.register_alias("mcl_core:jungletree_bark","mcl_trees:bark_jungle")
core.register_alias("mcl_core:sprucetree_bark","mcl_trees:bark_spruce")
core.register_alias("mcl_core:tree_bark","mcl_trees:bark_oak")
core.register_alias("mcl_crimson:warped_hyphae_bark","mcl_trees:bark_warped")
core.register_alias("mcl_crimson:crimson_hyphae_bark","mcl_trees:bark_crimson")
core.register_alias("mcl_mangrove:mangrove_tree_bark","mcl_trees:bark_mangrove")
core.register_alias("mcl_cherry_blossom:cherrytree_bark","mcl_trees:bark_cherry_blossom")

core.register_alias("mcl_core:birchsapling","mcl_trees:sapling_birch")
core.register_alias("mcl_core:big_oaksapling","mcl_trees:sapling_dark_oak")
core.register_alias("mcl_core:darksapling","mcl_trees:sapling_dark_oak")
core.register_alias("mcl_core:acaciasapling","mcl_trees:sapling_acacia")
core.register_alias("mcl_core:junglesapling","mcl_trees:sapling_jungle")
core.register_alias("mcl_core:sprucesapling","mcl_trees:sapling_spruce")
core.register_alias("mcl_core:sapling","mcl_trees:sapling_oak")
core.register_alias("default:sapling","mcl_trees:sapling_oak")
core.register_alias("mcl_cherry_blossom:cherrysapling","mcl_trees:sapling_cherry_blossom")

core.register_alias("mcl_flowerpots:flower_pot_birchsapling","mcl_flowerpots:flower_pot_sapling_birch")
core.register_alias("mcl_flowerpots:flower_pot_big_oaksapling","mcl_flowerpots:flower_pot_sapling_dark_oak")
core.register_alias("mcl_flowerpots:flower_pot_darksapling","mcl_flowerpots:flower_pot_sapling_dark_oak")
core.register_alias("mcl_flowerpots:flower_pot_acaciasapling","mcl_flowerpots:flower_pot_sapling_acacia")
core.register_alias("mcl_flowerpots:flower_pot_junglesapling","mcl_flowerpots:flower_pot_sapling_jungle")
core.register_alias("mcl_flowerpots:flower_pot_sprucesapling","mcl_flowerpots:flower_pot_sapling_spruce")
core.register_alias("mcl_flowerpots:flower_pot_sapling","mcl_flowerpots:flower_pot_sapling_oak")
core.register_alias("mcl_flowerpots:flower_pot_bamboo_plant","mcl_flowerpots:flower_pot_bamboo")

core.register_alias("mcl_fences:fence","mcl_fences:oak_fence")
core.register_alias("mcl_mangrove:mangrove_wood_fence","mcl_fences:mangrove_fence")
core.register_alias("mcl_crimson:crimson_fence","mcl_fences:crimson_fence")
core.register_alias("mcl_crimson:warped_fence","mcl_fences:warped_fence")
core.register_alias("mcl_cherry_blossom:cherry_fence","mcl_fences:cherry_blossom_fence")
core.register_alias("mcl_bamboo:bamboo_fence","mcl_fences:bamboo_fence")

core.register_alias("mcl_fences:fence_gate","mcl_fences:oak_fence_gate")
core.register_alias("mcl_mangrove:mangrove_wood_fence_gate","mcl_fences:mangrove_fence_gate")
core.register_alias("mcl_crimson:crimson_fence_gate","mcl_fences:crimson_fence_gate")
core.register_alias("mcl_crimson:warped_fence_gate","mcl_fences:warped_fence_gate")

core.register_alias("mcl_fences:fence_gate_open","mcl_fences:oak_fence_gate_open")
core.register_alias("mcl_cherry_blossom:cherry_fence_gate","mcl_fences:cherry_blossom_fence_gate")
core.register_alias("mcl_bamboo:bamboo_fence_gate","mcl_fences:bamboo_fence_gate")

core.register_alias("mclx_fences:nether_brick_fence_gate","mcl_fences:nether_brick_fence_gate")
core.register_alias("mclx_fences:red_nether_brick_fence_gate","mcl_fences:red_nether_brick_fence_gate")

core.register_alias("mclx_fences:nether_brick_fence_gate_open","mcl_fences:nether_brick_fence_gate_open")
core.register_alias("mclx_fences:red_nether_brick_fence_gate_open","mcl_fences:red_nether_brick_fence_gate_open")

core.register_alias("mclx_fences:nether_brick_fence","mcl_fences:nether_brick_fence")
core.register_alias("mclx_fences:red_nether_brick_fence","mcl_fences:red_nether_brick_fence")

core.register_alias("mcl_mangrove:mangrove_wood_fence_gate_open","mcl_fences:mangrove_fence_gate_open")
core.register_alias("mcl_crimson:warped_fence_gate_open","mcl_fences:warped_fence_gate_open")
core.register_alias("mcl_crimson:crimson_fence_gate_open","mcl_fences:crimson_fence_gate_open")
core.register_alias("mcl_bamboo:bamboo_fence_gate_open","mcl_fences:bamboo_fence_gate_open")
core.register_alias("mcl_cherry_blossom:cherry_fence_gate_open","mcl_fences:cherry_blossom_fence_gate_open")

core.register_alias("mcl_core:stripped_oak","mcl_trees:stripped_oak")
core.register_alias("mcl_core:stripped_jungle","mcl_trees:stripped_jungle")
core.register_alias("mcl_core:stripped_acacia","mcl_trees:stripped_acacia")
core.register_alias("mcl_core:stripped_dark_oak","mcl_trees:stripped_dark_oak")
core.register_alias("mcl_core:stripped_spruce","mcl_trees:stripped_spruce")
core.register_alias("mcl_core:stripped_birch","mcl_trees:stripped_birch")
core.register_alias("mcl_mangrove:mangrove_stripped_trunk","mcl_trees:stripped_mangrove")
core.register_alias("mcl_crimson:stripped_warped_hyphae","mcl_trees:stripped_warped")
core.register_alias("mcl_crimson:stripped_crimson_hyphae","mcl_trees:stripped_crimson")
core.register_alias("mcl_bamboo:bamboo_block_stripped","mcl_trees:stripped_bamboo")
core.register_alias("mcl_cherry_blossom:stripped_cherrytree","mcl_trees:stripped_cherry_blossom")

core.register_alias("mcl_core:stripped_oak_bark","mcl_trees:bark_stripped_oak")
core.register_alias("mcl_core:stripped_jungle_bark","mcl_trees:bark_stripped_jungle")
core.register_alias("mcl_core:stripped_acacia_bark","mcl_trees:bark_stripped_acacia")
core.register_alias("mcl_core:stripped_dark_oak_bark","mcl_trees:bark_stripped_dark_oak")
core.register_alias("mcl_core:stripped_spruce_bark","mcl_trees:bark_stripped_spruce")
core.register_alias("mcl_core:stripped_birch_bark","mcl_trees:bark_stripped_birch")
core.register_alias("mcl_mangrove:mangrove_stripped_bark","mcl_trees:bark_stripped_mangrove")
core.register_alias("mcl_crimson:stripped_warped_hyphae_bark","mcl_trees:bark_stripped_warped")
core.register_alias("mcl_crimson:stripped_crimson_hyphae_bark","mcl_trees:bark_stripped_crimson")
core.register_alias("mcl_cherry_blossom:stripped_cherrytree_bark","mcl_trees:bark_stripped_cherry_blossom")

core.register_alias("mcl_cherry_blossom:pressure_plate_cherrywood_on","mcl_pressureplates:pressure_plate_cherry_blossom_on")
core.register_alias("mcl_cherry_blossom:pressure_plate_cherrywood_off","mcl_pressureplates:pressure_plate_cherry_blossom_off")

local function alias_signs(oldwood,newwood)
	core.register_alias("mcl_signs:wall_sign"..oldwood, "mcl_signs:wall_sign".. newwood)
end --standing signs conversion in mcl_signs/compat.lua
core.register_alias("mcl_signs:sign","mcl_signs:wall_sign_oak")

alias_signs("","_oak")
alias_signs("_acaciawood","_acacia")
alias_signs("_junglewood","_jungle")
alias_signs("_birchwood","_birch")
alias_signs("_darkwood","_dark_oak")
alias_signs("_sprucewood","_spruce")
alias_signs("_mangrove_wood","_mangrove")
alias_signs("_crimson_hyphae_wood","_crimson")
alias_signs("_warped_hyphae_wood","_warped")
alias_signs("_cherrywood","_cherry_blossom")

core.register_alias("mcl_boats:boat","mcl_boats:boat_oak")
core.register_alias("mcl_boats:boat_cherry","mcl_boats:boat_cherry_blossom")
core.register_alias("mcl_boats:boat_obsidian","mcl_boats:boat_oak")

local function alias_chest_boat(oldwood,newwood)
	newwood = newwood or oldwood
	core.register_alias("mcl_boats:chest_boat"..oldwood,"mcl_boats:boat"..newwood.."_chest")
end
alias_chest_boat("","_oak")
alias_chest_boat("_acacia")
alias_chest_boat("_birch")
alias_chest_boat("_cherry", "_cherry_blossom")
alias_chest_boat("_dark_oak")
alias_chest_boat("_jungle")
alias_chest_boat("_mangrove")
alias_chest_boat("_spruce")
