core.register_alias("mcl_jukebox:record_1", "mcl_jukebox:record_13")
core.register_alias("mcl_jukebox:record_2", "mcl_jukebox:record_wait")
core.register_alias("mcl_jukebox:record_3", "mcl_jukebox:record_blocks")
core.register_alias("mcl_jukebox:record_4", "mcl_jukebox:record_far")
core.register_alias("mcl_jukebox:record_5", "mcl_jukebox:record_chirp")
core.register_alias("mcl_jukebox:record_6", "mcl_jukebox:record_strad")
core.register_alias("mcl_jukebox:record_7", "mcl_jukebox:record_mellohi")
core.register_alias("mcl_jukebox:record_8", "mcl_jukebox:record_mall")
