-- nodes to be automatically removed from the map:
--
local bad_nodes = {
	"mcl_structures:structblock_ancient_hermitage",
	"mcl_structures:structblock_azalea_tree",
	"mcl_structures:structblock_basalt_column",
	"mcl_structures:structblock_basalt_pillar",
	"mcl_structures:structblock_boulder",
	"mcl_structures:structblock_clay_pool",
	"mcl_structures:structblock_cold_ocean_ruins",
	"mcl_structures:structblock_desert_temple",
	"mcl_structures:structblock_desert_well",
	"mcl_structures:structblock_end_boat",
	"mcl_structures:structblock_end_exit_portal",
	"mcl_structures:structblock_end_exit_portal_open",
	"mcl_structures:structblock_end_gateway_portal",
	"mcl_structures:structblock_end_shipwreck",
	"mcl_structures:structblock_end_shrine",
	"mcl_structures:structblock_end_spawn_obsidian_platform",
	"mcl_structures:structblock_end_spike",
	"mcl_structures:structblock_fallen_tree",
	"mcl_structures:structblock_fossil",
	"mcl_structures:structblock_geode",
	"mcl_structures:structblock_ice_spike_large",
	"mcl_structures:structblock_ice_spike_small",
	"mcl_structures:structblock_igloo",
	"mcl_structures:structblock_jungle_temple",
	"mcl_structures:structblock_lavadelta",
	"mcl_structures:structblock_lavapool",
	"mcl_structures:structblock_mineshaft",
	"mcl_structures:structblock_nether_bridge",
	"mcl_structures:structblock_nether_bulwark",
	"mcl_structures:structblock_nether_outpost",
	"mcl_structures:structblock_nether_outpost_with_bridges",
	"mcl_structures:structblock_nether_portal",
	"mcl_structures:structblock_nether_portal_open",
	"mcl_structures:structblock_ocean_temple",
	"mcl_structures:structblock_pillager_outpost",
	"mcl_structures:structblock_ruined_portal_nether",
	"mcl_structures:structblock_ruined_portal_overworld",
	"mcl_structures:structblock_shipwreck",
	"mcl_structures:structblock_small_end_city",
	"mcl_structures:structblock_stairs_test",
	"mcl_structures:structblock_warm_ocean_ruins",
	"mcl_structures:structblock_water_lake",
	"mcl_structures:structblock_water_lake_mangrove_swamp",
	"mcl_structures:structblock_witch_hut",
	"mcl_structures:structblock_woodland_cabin",
	"mcl_structures:structblock_wood_test",
}

--lbm for secondary structures (structblock included in base structure)
core.register_lbm({
	name = "mcl_map_dross:remove_structblocks",
	run_at_every_load = true,
	nodenames = bad_nodes,
	action = function(pos, node)
		core.remove_node(pos)
	end
})
